Remove GitHub plugin
Our scans fails due to:

  ERROR: Error during SonarQube Scanner execution
  ERROR: Unable to load component class org.sonar.scanner.scan.ProjectLock
  ERROR: Caused by: Unable to load component class org.sonar.scanner.scan.DefaultInputModuleHierarchy
  ERROR: Caused by: Unable to load component class org.sonar.scanner.scan.ProjectBuildersExecutor
  ERROR: Caused by: Unable to load component class org.sonar.plugins.github.PullRequestProjectBuilder
  ERROR: Caused by: org.sonar.plugins.github.PullRequestProjectBuilder has unsatisfied dependency 'class org.sonar.plugins.github.PullRequestFacade' for constructor 'public org.sonar.plugins.github.PullRequestProjectBuilder(org.sonar.plugins.github.GitHubPluginConfiguration,org.sonar.plugins.github.PullRequestFacade,org.sonar.api.batch.AnalysisMode)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@666b83a4:234<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@e70f13a:9<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@4cc547a:51<|

So let's just get rid of this plugin... Se inline code comment for
more context.